DELETE server.unique-apps.de:9006/Marcel
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJNYXJjZWwiLCJpYXQiOjE1NjAyNDM1ODgsImV4cCI6MTU2MTEwNzU4OH0.EDv3kcgiTMHzXVT5VfQft0Kfd_BYtX6HPmCtLXq3ouR5tkVO5QgY8LKc7_CFuyMT9UCXnq-7sk3PIjZ8M5Mrpw

###